### ISSUE TITLE
Feature Request - Add to Home Assistant

### ISSUE THREAD

**Issue by samAheenan** [matthuisman/electrickiwi.api#2]
Kia ora Matt,

Would you consider contributing this to [Home Assistant Operating System](https://github.com/home-assistant/operating-system) so it can be used as an Integration in the same way someone has done so for [Flick Electric](https://www.home-assistant.io/integrations/flick_electric/)?

Cheers,
Sam.

**Comment by mikey0000** [comment]
Hi I'm working on home assistant integration already have PR into HA and python api published to pypi. @matthuisman welcome to collaborate.
